### ISSUE TITLE
.clang-format: два раза указана опция SplitEmptyNamespace

### ISSUE THREAD

**Issue by anzotov** [dsaa27/prosoftschool2023#1]
Приветствую! clang-format ругается на файл .clang-format:
>prosoftschool2023/.clang-format:113:5: error: duplicated mapping key 'SplitEmptyNamespace'
>    SplitEmptyNamespace: true
>    ^~~~~~~~~~~~~~~~~~~
>Error reading prosoftschool2023/.clang-format: Invalid argument

https://github.com/dsaa27/prosoftschool2023/blob/216ce96ecf408f55b0ba174bc8a5514383301590/.clang-format#L109

https://github.com/dsaa27/prosoftschool2023/blob/216ce96ecf408f55b0ba174bc8a5514383301590/.clang-format#L113

**Comment by dsaa27** [comment]
Благодарю за замечание!
Исправил
